### ISSUE TITLE
It's possible to proxy Websocket? 

### ISSUE THREAD

**Issue by Simonefardella** [jazzband/django-revproxy#109]
Hi, i'm trying to proxy behind django Node-Red, a node-based programming tool for IoT.

This application, uses heavily Webosocket in order to communicate with remote MQTT brokers, Websockets, etc...

Actually, i've tried to do some tests and the proxied http content works good, but the WS content it's not working, and django-channels complains that the route was not found...i'm not sure if this package supports websocket proxying, can someone will solve this doubt?

Thanks!

**Comment by seocam** [comment]
Hello @Simonefardella!

Django revproxy was initially conceived to work with HTTP(s) only so I would guess it wouldn't work with WS. In the other hand supporting WS wouldn't be a bad idea at all. 

If you have time to take a look in the code to help us figure out how to support WS your help would be very much appreciated!

**Comment by Archmonger** [comment]
Closing in favor of #122
