### ISSUE TITLE
AttributeError: 'HttpResponse' object has no attribute '_headers'

### ISSUE THREAD

**Issue by sbds** [jazzband/django-revproxy#126]
This statement is producing an error:
  logger.debug('Response headers: %s', getattr(response, '_headers'))

In these 2 files:
  "...lib64/python3.7/site-packages/revproxy/utils.py", line 127, in set_response_headers
  "...lib64/python3.7/site-packages/revproxy/response.py", line 48, in get_django_response

**Comment by litghost** [comment]
This was changed a while ago: https://github.com/django/django/commit/bcc2befd0e9c1885e45b46d0b0bcdc11def8b249

**Comment by sbds** [comment]
Oh. It isn't changed in the version installed though PIP.

**Comment by litghost** [comment]
> Oh. It isn't changed in the version installed though PIP.

Sorry, I'm agreeing with this issue, and the django change is pretty old.

**Comment by mhoonjeon** [comment]
Experiencing the same issue here

**Comment by matteing** [comment]
Same here.

**Comment by ak55mm** [comment]
Any idea when this will be in master? Everyone who has moved to Django 3.2 will be affected by this.

**Comment by stolpeo** [comment]
Is there an estimate when this will be merged?

**Comment by metalshanked** [comment]
any update or estimate on when this will be available on PyPi? Thanks!

**Comment by brianmay** [comment]
I think this project is basically dead, sorry. I was working on it a while back, but no longer working on the project or employer that required it.

Best bet might be to fork it, change the name, and upload the new name to PyPI.

**Comment by thatsed** [comment]
@brianmay what about transferring the project to Jazzband? That would make it easier for everyone involved.

If you're able, please reach out to @seocam about this. There's quite a community around this project, it would fit nicely in the Jazzband collective in my opinion.

If that's off the table for any reason, we will mantain our fork over at https://github.com/Innovativity/django-revproxy for LTS Django releases and we'll provide a new PyPI package to keep the project alive. That would be a backup solution though.

**Comment by brianmay** [comment]
Who is Jazzband?

There have been times abandoned projects get transferred to new maintainers, who then abuse the privilege, and introduce malware into new releases. Which means the project is in even worse state then just being abandoned. Wouldn't want to do that here.

Technically this isn't my project, @seocam was maintaining it, until he ran out of time https://github.com/TracyWebTech/django-revproxy/issues/75#issuecomment-391316947. I was granted full access https://github.com/TracyWebTech/django-revproxy/issues/75#issuecomment-391689052 to the github project, pypi, and readthedocs (did I miss anything?). Unless anybody raises objections, I think I can make any change in the best interests of this project.

If my understanding of [Jazzband](https://jazzband.co/) is correct, it is probably a good home for this project. Although I have no idea what to do with PyPI and readthedocs access, which probably will also be required.

**Comment by thatsed** [comment]
> There have been times abandoned projects get transferred to new maintainers, who then abuse the privilege, and introduce malware into new releases. Which means the project is in even worse state then just being abandoned. Wouldn't want to do that here.

That's unfortunately very true, and part of the reasoning behind Jazzband

> Technically this isn't my project, @seocam was maintaining it, until he ran out of time #75 (comment). I was granted full access #75 (comment) to the github project, pypi, and readthedocs (did I miss anything?). Unless anybody raises objections, I think I can make any change in the best interests of this project.

I think, but I may be wrong, only the owner can transfer the repo. That's why I proposed to raise the question to @seocam, sorry it came out that way, I didn't mean to doubt your position!

> Although I have no idea what to do with PyPI and readthedocs access, which probably will also be required.

That's something that should be discussed with them later on I think.

Thank you @brianmay for your help with this!

**Comment by dimasanwaraziz** [comment]
Hello, any solution for this case? I still have issue with this

`'HttpResponse' object has no attribute '_headers'`

**Comment by bode135** [comment]
Same here...

**Comment by dimasanwaraziz** [comment]
Please, anyone have solution?

**Comment by Germey** [comment]
Same issue

**Comment by bode135** [comment]
Same issue

**Comment by Germey** [comment]
Install the master branch should work

**Comment by AnhHoTrungDev** [comment]
Same issue on mac 14 m1, Django version 4.0.7, any idea?
<img width="666" alt="image" src="https://user-images.githubusercontent.com/38943998/214003753-591c135c-8d34-42c6-8c68-09ecefdb2262.png">

**Comment by JPereira-FJB** [comment]
Same issue, some solution?

**Comment by studio-salamander** [comment]
@JPereira-FJB 
"Install the master branch should work" (c) @Germey

**Comment by andruten** [comment]
You can also try this: https://github.com/jazzband/help/issues/330#issuecomment-1506712843
