### ISSUE TITLE
ModuleNotFoundError: No module named 'kerberosrevproxy'

### ISSUE THREAD

**Issue by dimasanwaraziz** [jazzband/django-revproxy#158]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/50611785/205818564-fafea4c6-6088-448d-a822-d7251a811a28.png">

**Comment by brianmay** [comment]
I don't think that is anything to do with this package. I did a search here for `kerberosrevproxy` and couldn't find any matches.
